# theme: jekyll-theme-leap-day

# Site settings
title: Joseph E. Gonzalez
email: jegonzal@berkeley.edu 
description: Joseph E. Gonzalez

author :
  name : Joseph E. Gonzalez
  email : jegonzal@berkeley.edu
  github : jegonzal.github.io

# Build settings
# permalink: :title/
sass:
  sass_dir: css


plugins: ["jekyll-sitemap"]

