# theme: jekyll-theme-leap-day

# Site settings
title: Joseph E. Gonzalez
email: jegonzal@berkeley.edu 
author: Joseph E. Gonzalez
description: Joseph E. Gonzalez


# Build settings
# permalink: :title/
sass:
  sass_dir: css


plugins: ["jekyll-sitemap"]

